version: '3.9'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    build: ./
    volumes:
      - ./:/var/www/app
    links:
      - redis
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    command:
      sh -c 'npm i && npm run dev'
volumes:
  redis:
    driver: local
